#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-PerlIO-eol
Version  : 0.17
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/PerlIO-eol-0.17.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/PerlIO-eol-0.17.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libp/libperlio-eol-perl/libperlio-eol-perl_0.17-1.debian.tar.xz
Summary  : 'PerlIO layer for normalizing line endings'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-PerlIO-eol-lib
Requires: perl-PerlIO-eol-license
Requires: perl-PerlIO-eol-man

%description
normalizing line endings.  It requires Perl version 5.7.3 or later.
* Installation

%package lib
Summary: lib components for the perl-PerlIO-eol package.
Group: Libraries
Requires: perl-PerlIO-eol-license

%description lib
lib components for the perl-PerlIO-eol package.


%package license
Summary: license components for the perl-PerlIO-eol package.
Group: Default

%description license
license components for the perl-PerlIO-eol package.


%package man
Summary: man components for the perl-PerlIO-eol package.
Group: Default

%description man
man components for the perl-PerlIO-eol package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n PerlIO-eol-0.17
mkdir -p %{_topdir}/BUILD/PerlIO-eol-0.17/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/PerlIO-eol-0.17/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-PerlIO-eol
cp LICENSE %{buildroot}/usr/share/doc/perl-PerlIO-eol/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/PerlIO/eol.pm

%files lib
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/auto/PerlIO/eol/eol.so

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-PerlIO-eol/LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/PerlIO::eol.3
